### ISSUE TITLE
TTS 버튼 클릭시 버튼 색깔이 변하지 않는 문제

### ISSUE THREAD

**Issue by ner-di-dream** [CSID-DGU/2023-1-OSSP2-NotEasy-10#31]
TTS 버튼을 클릭하면 음성이 나오는 동안 버튼 색깔이 변하고, 음성이 끝나면 버튼 색깔이 원래대로 돌아와야 하는데, 이에 대해 수정이 필요합니다.

**Comment by juhno1023** [comment]
setAudio(() => playAudio);
setIsAudio(() => true);
playAudio.play();
playAudio.onended = () => {
setIsAudio(() => false);
 
오디오가 재생 중인지 상태를 판단하는 변수를 추가하여 해결하였습니다.
